services:
  - type: web
    name: api
    env: docker
    plan: free
    region: oregon
    dockerfilePath: ./apps/api/Dockerfile
    healthCheckPath: /
    envVars:
      DATABASE_URL: 
        fromDatabase:
          name: my-database
          property: connectionString

databases:
  - name: my-database
    region: oregon
    plan: free